# Generated by Django 2.0.1 on 2018-01-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180127_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_by',
        ),
        migrations.AddField(
            model_name='like',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
